FROM zt/alpine:v1

MAINTAINER hualei 834890137@qq.com

RUN apk add nodejs
RUN apk add npm
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN npm install webpack -g
RUN npm install --global vue-cli
